name: CI

on:
  push:
    branches: [ "main", "import/supercore" ]
  pull_request:
    branches: [ "main" ]

jobs:
  node:
    if: 
      contains(fromJSON('[''' + (if (False) { 'true' } else { 'false' }) + ''']'), true)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install
        run: npm ci || npm install
      - name: Lint
        run: npm run lint || echo "no lint script"
      - name: Test
        run: npm test --if-present
      - name: Build
        run: npm run build --if-present

  python:
    if: 
      contains(fromJSON('[''' + (if (False -or False) { 'true' } else { 'false' }) + ''']'), true)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install . || pip install -e .; fi
      - name: Lint
        run: |
          pip install flake8 || true
          flake8 || true
      - name: Test
        run: |
          pytest || echo "no tests yet"
